In [1]:
import pandas as pd
import numpy as np

In [2]:
address_url = "C:/Users/abhil/Desktop/Python/DataSet/hi.csv"
address = pd.read_csv(address_url)

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (2,7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
df = address[:1000]
df

,LON,LAT,NUMBER,STREET,UNIT,CITY,DISTRICT,REGION,POSTCODE,ID,HASH
0,-157.833127,21.300769,1625,CLARK ST HNL,NaN,HONOLULU,NaN,NaN,NaN,NaN,9b3cf2c890fa7e9d
1,-157.721942,21.289418,6152,KAWEKIU PL,NaN,NaN,NaN,NaN,NaN,NaN,6fa5d983b1a4dead
2,-157.722200,21.288880,6141,KAWEKIU PL,NaN,NaN,NaN,NaN,NaN,NaN,9ec61a48b879f0f3
3,-157.722751,21.290175,354,DALENE WAY,NaN,NaN,NaN,NaN,NaN,NaN,30b9cf496ad7d6e8
4,-157.724095,21.370414,1477,HUMUWILI PL,NaN,NaN,NaN,NaN,NaN,NaN,9da8e82c2d0508f6
5,-157.723510,21.369894,1486,HUMUWILI PL,NaN,NaN,NaN,NaN,NaN,NaN,3c07602f227355a1
6,-157.723346,21.370603,1469,HUMUULA ST,NaN,NaN,NaN,NaN,NaN,NaN,d0b56f55c1106112
7,-157.722639,21.369971,1499,HUMUULA ST,NaN,NaN,NaN,NaN,NaN,NaN,0dcae1322c0e5a85
8,-157.723396,21.369216,1428,ONIONI ST,NaN,NaN,NaN,NaN,NaN,NaN,62c880d4437ae984
9,-157.722406,21.369498,1460,ONIONI ST,NaN,NaN,NaN,NaN,NaN,NaN,cf2feebb7a6f6221
10,-158.182491,21.438742,86-78,HOAHA ST,NaN,NaN,NaN,NaN,NaN,NaN,5888666f2a2d1c32
11,-157.724064,21.394007,531,KAWAILOA RD,A,NaN,NaN,NaN,NaN,NaN,c006b45cec420977
12,-157.724005,21.394350,527,KAWAILOA RD,NaN,NaN,NaN,NaN,NaN,NaN,5222deb53185c0fa
13,-158.102806,21.591837,62-103,ANAHULU PL,NaN,NaN,NaN,NaN,NaN,NaN,13b28e8f6d20b634
14,-157.923679,21.648576,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,aaea796ee7b8d4d1
15,-158.032432,21.404083,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12d969f678034d05
16,-157.857496,21.481120,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,afc645c082e5f51f
17,-157.747145,21.402566,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90f8c2818ec6f59f
18,-157.852518,21.482457,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,e9a2cea2cebfacf1
19,-158.039513,21.644256,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,e2b3700243b4d98b
20,-157.871313,21.309920,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dd85c2a6370f15fd
21,-158.060083,21.333681,91-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48c7a0c82367cb46
22,-157.987772,21.388771,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73dac882170d964c
23,-158.029405,21.403142,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ef87bdc7a41cd433
24,-157.827798,21.346220,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b4b0870480a4e316
25,-158.029075,21.685753,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2fb4964c93af811d
26,-157.855710,21.333927,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5f2326fa34ed55c6
27,-158.038295,21.521637,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f3335ae6ad0529a9
28,-157.861784,21.348267,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d9f43be9301593b1
29,-157.900835,21.374691,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b21117eb1d38deb5
...,...,...,...,...,...,...,...,...,...,...,...
970,-157.744009,21.402374,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19e3ef003ebc4d5e
971,-158.190683,21.473814,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bbb1379396147193
972,-158.088714,21.591414,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,d04a43994cdb3355
973,-157.863264,21.321805,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b192e371c6db2d67
974,-158.012642,21.312578,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7cdc0bc635464802
975,-157.910913,21.607306,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,a1bf3a04f2756699
976,-157.970394,21.377715,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,399940c0afa13fa7
977,-157.924131,21.632586,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90151b17b6859dce
978,-157.848614,21.440055,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0f84a81ed317d3d0
979,-157.846126,21.467229,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,e4306581493e9762
980,-157.816940,21.283559,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81d7cfc72ae3d23a
981,-157.955700,21.404623,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f1467d8bfba42901
982,-158.136601,21.382264,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48a49cd4c3a61b73
983,-157.934413,21.377736,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,c894745ee14fd009
984,-157.752885,21.293097,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2ab850487a053522
985,-158.009609,21.506303,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,e4b63e90ba623650
986,-157.806711,21.271787,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,de5b9c7a553b41d2
987,-157.919109,21.635688,55-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,cb9613a77bbfafa3
988,-157.715220,21.285984,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,750fd5b3e7c3a994
989,-157.849354,21.295246,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9fb08e26045eb830
990,-158.074982,21.329042,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dab8cb5008f48c54
991,-157.782257,21.264460,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30c6d238120cde43
992,-157.785304,21.305177,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,e70a343dc2c34883
993,-157.996028,21.481126,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49814a60c1b621a3
994,-157.747697,21.401466,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,973efd79f89065dc
995,-157.855873,21.508158,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,406c1d9874a91009
996,-158.016245,21.400887,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16b29c2ec72ccde8
997,-157.854937,21.556180,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01471733460d67bd
998,-157.850988,21.332609,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,279c37d1c1d07d26
999,-157.996134,21.413588,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74525c818d746a6d

In [4]:
df = df.drop(['NUMBER','STREET', 'UNIT','CITY', 'DISTRICT', 'REGION', 'POSTCODE', 'ID', 'HASH'], axis=1)

In [5]:
df.head()

          LON        LAT
0 -157.833127  21.300769
1 -157.721942  21.289418
2 -157.722200  21.288880
3 -157.722751  21.290175
4 -157.724095  21.370414

In [15]:
X = np.array(df)

In [16]:
X= X.astype(np.float)

In [17]:
rads = np.radians(X)
rads
df

            LON        LAT  Cluster
0   -157.833127  21.300769       26
1   -157.721942  21.289418       20
2   -157.722200  21.288880       20
3   -157.722751  21.290175       20
4   -157.724095  21.370414       -1
5   -157.723510  21.369894       -1
6   -157.723346  21.370603       -1
7   -157.722639  21.369971       -1
8   -157.723396  21.369216       -1
9   -157.722406  21.369498       -1
10  -158.182491  21.438742        4
11  -157.724064  21.394007       -1
12  -157.724005  21.394350       -1
13  -158.102806  21.591837        0
14  -157.923679  21.648576        3
15  -158.032432  21.404083       16
16  -157.857496  21.481120       -1
17  -157.747145  21.402566        9
18  -157.852518  21.482457       -1
19  -158.039513  21.644256        1
20  -157.871313  21.309920       -1
21  -158.060083  21.333681        7
22  -157.987772  21.388771       -1
23  -158.029405  21.403142       16
24  -157.827798  21.346220       -1
25  -158.029075  21.685753        1
26  -157.855710  21.333927       22
27  -158.038295  21.521637       -1
28  -157.861784  21.348267       23
29  -157.900835  21.374691       -1
..          ...        ...      ...
970 -157.744009  21.402374        9
971 -158.190683  21.473814        4
972 -158.088714  21.591414        0
973 -157.863264  21.321805       -1
974 -158.012642  21.312578       15
975 -157.910913  21.607306        3
976 -157.970394  21.377715       -1
977 -157.924131  21.632586        3
978 -157.848614  21.440055        5
979 -157.846126  21.467229        5
980 -157.816940  21.283559       25
981 -157.955700  21.404623       19
982 -158.136601  21.382264        4
983 -157.934413  21.377736       17
984 -157.752885  21.293097       -1
985 -158.009609  21.506303       -1
986 -157.806711  21.271787       25
987 -157.919109  21.635688        3
988 -157.715220  21.285984       20
989 -157.849354  21.295246       -1
990 -158.074982  21.329042       12
991 -157.782257  21.264460       -1
992 -157.785304  21.305177       -1
993 -157.996028  21.481126       -1
994 -157.747697  21.401466        9
995 -157.855873  21.508158       -1
996 -158.016245  21.400887       16
997 -157.854937  21.556180       -1
998 -157.850988  21.332609       22
999 -157.996134  21.413588       16

[1000 rows x 3 columns]

In [9]:
import hdbscan

In [10]:
kms_per_radian = 6371.0088
epsilon = 1.2 / kms_per_radian
clusterer = hdbscan.HDBSCAN(min_cluster_size=10, metric='haversine')
cluster_labels = clusterer.fit_predict(df)

In [11]:
df['Cluster']=cluster_labels

In [19]:
cluster_count = df.groupby('Cluster').count().sort_values(by=['LAT'],ascending=False)[:10]
cluster_count = cluster_count.drop(['LON'],axis=1)
x = cluster_count.LAT.keys()
cluster_count
num_clusters = len(set(cluster_labels))
clusters = pd.Series([rads[cluster_labels == n] for n in range(num_clusters)])
print('Number of clusters: {}'.format(num_clusters))

Number of clusters: 28

In [25]:
print(cluster_count)

         LAT
Cluster
-1       279
 6        78
 25       58
 19       53
 4        52
 16       50
 15       44
 9        42
 17       31
 14       30

In [24]:
from geopy.distance import great_circle
from shapely.geometry import MultiPoint
def get_centermost_point(cluster):
    centroid = (MultiPoint(cluster).centroid.x, MultiPoint(cluster).centroid.y)
    centermost_point = min(cluster, key=lambda point: great_circle(point, centroid).m)
    return tuple(centermost_point)

#x = np.ndarray()
for i in clusters[:len(clusters)-1]:
    x =  np.degrees(get_centermost_point(i))
    print(x)
    
#centermost_points = clusters.map(get_centermost_point)

[-158.1097766   21.5821793    0.       ]
[-158.0404161   21.6605608    1.       ]
[-157.966473    21.6767118    2.       ]
[-157.9134089   21.6148702    3.       ]
[-158.1828342   21.4410634    4.       ]
[-157.8363347   21.4444669    5.       ]
[-157.8019759   21.4115896    6.       ]
[-158.0587258   21.3358155    7.       ]
[-157.7236447   21.3427044    8.       ]
[-157.7432276   21.4012819    9.       ]
[-157.7566635   21.3776442   10.       ]
[-158.0835169   21.3557134   11.       ]
[-158.0722637   21.3338687   12.       ]
[-158.0043512   21.4542865   13.       ]
[-157.8952955   21.3404091   14.       ]
[-158.0143204   21.3195885   15.       ]
[-158.0101927   21.3950139   16.       ]
[-157.9215737   21.3771562   17.       ]
[-157.9370985   21.4070506   18.       ]
[-157.9573635   21.4023083   19.       ]
[-157.7147674   21.2864894   20.       ]
[-157.7387076   21.2844995   21.       ]
[-157.8509877   21.332609    22.       ]
[-157.8574189   21.3488571   23.       ]
[-157.7641892   21.2839455   24.       ]
[-157.8013804   21.285408    25.       ]
[-157.8243321   21.3083654   26.       ]

In [ ]:
a = np.degrees